name: Build OpenIPC Config Avalonia App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64, arm64]
        include:
          - os: macos-latest
            arch: arm64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Publish project
      run: dotnet publish -c Release -r ${{ matrix.os == 'ubuntu-latest' && 'linux-x64' || matrix.os == 'windows-latest' && 'win-x64' || (matrix.os == 'macos-latest' && matrix.arch == 'arm64' && 'osx-arm64') || 'osx-x64' }} --self-contained

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: OpenIPC-${{ matrix.os }}-${{ matrix.arch }}
        path: '**/bin/Release/net8.0/*' # Adjust the path to match your project's output folder